name: Docker-Image-Build-CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag cyborgbackup/cyborgbackup-ui:$(echo $GITHUB_SHA | cut -c 1-6)
      - name: Tag Docker Image to Latest
        run: docker tag cyborgbackup/cyborgbackup-ui:$(echo $GITHUB_SHA | cut -c 1-6) cyborgbackup/cyborgbackup-ui:latest
      - name: Push the tagged Docker image
        run: docker push cyborgbackup/cyborgbackup-ui
