name: Docker-Image-Build-CI-DEV

on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag cyborgbackup/cyborgbackup-ui:dev-${{ env.GITHUB_SHA_SHORT }}
      - name: Tag Docker Image to Develop
        run: docker tag cyborgbackup/cyborgbackup-ui:dev-${{ env.GITHUB_SHA_SHORT }} cyborgbackup/cyborgbackup-ui:develop
      - name: Push the tagged Docker image
        run: docker push cyborgbackup/cyborgbackup-ui:dev-${{ env.GITHUB_SHA_SHORT }}

  debian-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
        with:
          artifacts_directory: output
      - uses: actions/upload-artifact@v1
        with:
          name: debian-package
          path: output
