name: Docker-Image-Build-CI-DEV

on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag cyborgbackup/cyborgbackup-ui:dev-$(echo $GITHUB_SHA | cut -c 1-6)
      - name: Tag Docker Image to Develop
        run: docker tag cyborgbackup/cyborgbackup-ui:dev-$(echo $GITHUB_SHA | cut -c 1-6) cyborgbackup/cyborgbackup-ui:develop
      - name: Push the tagged Docker image
        run: docker push --all-tags cyborgbackup/cyborgbackup-ui

  debian-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
        with:
          artifacts_directory: output
      - uses: actions/upload-artifact@v1
        with:
          name: debian-package
          path: output

  linux-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install, build, and test
        run: |
          npm install
          npm run build:electron
      - name: Electron-Builder Linux App
        run: npm run package:linux
      - uses: actions/upload-artifact@v2
        with:
          name: cyborgbackup-linux-app.AppImage
          path: packages/cyborgbackup-*.AppImage
      - uses: actions/upload-artifact@v2
        with:
          name: cyborgbackup-linux-app.snap
          path: packages/cyborgbackup-*.snap
      - uses: actions/upload-artifact@v2
        with:
          name: cyborgbackup-linux-app.deb
          path: packages/cyborgbackup-*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: cyborgbackup-linux-app.rpm
          path: packages/cyborgbackup-*.rpm

  windows-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install, build, and test
        run: |
          sudo apt install wine
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install wine32
          npm install
          npm run build:electron
      - name: Electron-Builder Linux App
        run: npm run package:win
      - uses: actions/upload-artifact@v2
        with:
          name: cyborgbackup-win-app.exe
          path: packages/cyborgbackup-*.exe

  macos-app:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install, build, and test
        run: |
          npm install
          npm run build:electron
      - name: Electron-Builder Linux App
        run: npm run package:mac
      - uses: actions/upload-artifact@v2
        with:
          name: cyborgbackup-mac-app.dmg
          path: packages/cyborgbackup.*.dmg